version: "3"
services: 
  demo-cli:
    build: ./demo-cli
    environment: 
      MICRO_REGISTRY: "mdns"
  
  demo-service:
    build: ./demo-service
    ports:
      - "9091:9091"
    environment: 
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      
  user-service:
    depends_on:
      - user-db
    build: ./user-service
    ports:
      - "9092:9091"
    environment: 
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "user-db:3306"
      DB_NAME: "micro_shop_user"
      DB_USER: "test"
      DB_PASSWORD: "test"
  user-db:
    image: mysql:5.7
    container_name: user-db
    command: --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: micro_shop_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test

volumes:
  db_data: {}